### ISSUE TITLE
Error for mygene when trying to filter padlocks 

### ISSUE THREAD

**Issue by leviay** [AlexBecalick/padlock_validation#1]
Hi,
I'm currently generating df_padlock_filtered in read_blast_queries.ipynb but I'm encountering this error when running the code block:
`HTTPError: 429 Client Error: Too Many Requests for url: http://mygene.info/v3/query/?species=human&size=20&q=UNC5D`

Is there any way to get around this?

Thank you!

**Comment by AlexBecalick** [comment]
Hi Levia,

I couldn't replicate your exact issue when I tried with random genes. Perhaps if you send me a copy of your df_padlock file I can recreate it. In the meantime, I've tried adding a backoff factor on the HTTP requests which hopefully will solve that issue. Please try it out and let me know how it goes.

**Comment by leviay** [comment]
Hi Alex,

Thank you for your reply. Unfortunately, I'm still getting the same issue, even with the backoff factor. Here is my df_padlock file!
[df_padlock.csv](https://github.com/user-attachments/files/16346357/df_padlock.csv)

**Comment by AlexBecalick** [comment]
Strange, I still couldn't replicate the issue. Some googling suggests that some sites will block certain IPs that have had high request rates in the past, perhaps its a university IP issue? You could try changing your IP address if you want to use it again in the future. The rate limiter should prevent problems.

For this specific df_padlock I've run it for you on my working setup and got this result:
[df_gene_filtered_leviay.csv](https://github.com/user-attachments/files/16360937/df_gene_filtered_leviay.csv)
[df_padlock_filtered_leviay.csv](https://github.com/user-attachments/files/16360938/df_padlock_filtered_leviay.csv)

There's some offtarget genes here for many of the padlocks you generated. I would first check the df_filtered output and see what the severity of these offtarget site are. If you sort by e-value, what is the smallest e-value you find? (or send the df_filtered and I can take a look)

**Comment by leviay** [comment]
Amazing thanks so much!
[df_filtered.csv](https://github.com/user-attachments/files/16361217/df_filtered.csv)
It looks like the smallest e-value I have is 0.000366.
I've also just filtered out the offtarget padlocks from the original padlocks that I generated, is this okay to do?

**Comment by AlexBecalick** [comment]
Great, just looked over the csv. Looks like all those offtarget hits are weak which is good. You certainly can just filter the offtarget padlocks out from the original padlock list as the safest way to go. 

However if you find that you don't have enough padlocks left for a specific gene, you can be sure that these offtarget hits shown here are weak enough to reintroduce some of those filtered out padlocks back in if necessary. Given the original criteria for defining non-specific hits (found in the 3rd cell of read_blast_queries:
    # Exclude hits with less than 50% coverage and less than 80% homology
    #df = df.loc[df[2] > 80]
    #df = df[df[3] > 2*armlength*0.5]

    # Penalise gaps in the hits
    #df = df.loc[df[6] < armlength - 4]
    #df = df.loc[df[7] > armlength + 5]
    
  I think all of the offtarget hits found here would not pass those thresholds and wouldn't be classed as a true offtarget site. You can try that yourself to make sure. 
  
  Good luck with the padlocks!

**Comment by leviay** [comment]
Thank you!
